# Generated by Django 4.2.4 on 2023-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sprite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20)),
                ("x_pos", models.IntegerField(default=0)),
                ("y_pos", models.IntegerField(default=0)),
            ],
        ),
    ]
